name: Bug
description: Report a bug
labels: ["type:bug"]
body:
  - type: input
    id: summary
    attributes:
      label: Summary
      placeholder: e.g. 500 on POST /auth/login with valid credentials
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Start docker
        2. POST /auth/login with payload { ... }
        3. Observe 500
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected
  - type: textarea
    id: actual
    attributes:
      label: Actual
  - type: textarea
    id: logs
    attributes:
      label: Logs / Screenshots
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options: ["P1","P2","P3"]
      default: 1